# backend/src/main/resources/application-offline.yml
spring:
  config:
    activate:
      on-profile: offline
  datasource:
    url: jdbc:h2:file:./data/offline/offline_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect

app:
  mode: offline
  storage:
    file:
      path: ./data/workflows